name: swapTech
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  barcode_scan: ^3.0.1
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.13.7
  connectivity: ^0.4.9
  contacts_service: ^0.4.6
  country_pickers: ^1.2.0
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  esys_flutter_share: ^1.0.2
  file_picker: ^2.0.6
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_dynamic_links: null
  firebase_messaging: ^6.0.9
  firebase_storage: ^3.1.6
  flutter_advanced_networkimage: any
  flutter_country_picker: ^0.1.6
  flutter_icons: ^1.0.0+1
  flutter_image_compress: ^0.6.3
  flutter_speed_dial: ^1.2.5
  fluttertoast: ^7.1.1
  font_awesome_flutter: ^8.8.1
  geocoder: ^0.2.1
  geolocator: ^5.3.2+2
  get: ^3.15.0
  google_fonts: ^0.3.10
  google_sign_in: ^4.5.1
  image_cropper: ^1.0.2
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  let_log: ^1.1.4
  location: ^3.0.2
  mask_text_input_formatter: ^1.0.7
  modal_progress_hud: ^0.1.3
  native_contact_dialog: ^0.2.2
  network_image_to_byte: ^0.0.1
  permission_handler: ^5.0.1+1
  pin_code_fields: ^2.3.0+3
  provider: ^4.3.2+2
  qr_flutter: ^3.2.0
  share: ^0.6.2+3
  swipe_gesture_recognizer: ^0.0.2
  url_launcher: ^5.5.0
  flutter_widgetkit: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Book.otf
        - asset: assets/fonts/Gotham-Medium.otf
        - asset: assets/fonts/Gotham-Thin.otf
        - asset: assets/fonts/Gotham-Ultra.otf
        - asset: assets/fonts/GothamNarrow-Black.otf
        - asset: assets/fonts/GothamNarrow-Book.otf
        - asset: assets/fonts/GothamNarrow-Thin.otf
        - asset: assets/fonts/GothamNarrow-Ultra.otf
    - family: Gotham-Light
      fonts:
        - asset: assets/fonts/Gotham-Light.otf
    - family: Gotham-Book
      fonts:
        - asset: assets/fonts/Gotham-Book.otf
    - family: Gotham-Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.otf
    - family: Helvetica-Regular
      fonts:
        - asset: assets/fonts/NewHelvetica-Regular.otf
